<h1 style="color:#6C3483" align = "center">Arrays and Numpy</h1>

Array Library

In [ ]:
######### Array in python #########
"""
1. Arrays are collection of homogeneous datatypes.
2. Types: i-->signed int, I --> unsigned int, f---> float, d--->double, L ---> unsigned Long, l ---> signed long,
u--->char.
"""

'\n1. Arrays are collection of homogeneous datatypes.\n2. Types: i-->signed int, I --> unsigned int, f---> float, d--->double, L ---> unsigned Long, l ---> signed long,\nu--->char.\n'

In [ ]:
from array import *               # By default arrays are not supported, you need to import the array module.
# import array as arr

In [ ]:
vals = array('i', [1,2,3,4,5])

In [ ]:
vals1 = array('i', [1,2,3,4,6]) # Heterogenous data not supported

In [ ]:
val3 = vals+vals1                # not getting elementwise sums. One is appended with other. Elementwise sum in numpy.
val3

array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 6])

In [ ]:
vals = array('I', [1,2,3,-4,5])  # Unsigned int, both positive and negative values are not supported together

OverflowError: can't convert negative value to unsigned int

In [ ]:
vals1 = array('i', [1,2,3,-4,5]) # Signed int, both positive and negative values are supported

In [ ]:
cval3 = vals+vals1                # not getting elementwise sums. One is appended with other. Elementwise sum in numpy.
val3

array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 6])

In [ ]:
c = array('u', ['A', ' ', 'B', ' ', 'C'])   # u (unicode) --> charecters
c

array('u', 'A B C')

In [ ]:
print(vals.buffer_info()) # Returns a tuple with initial address of the array with the number of elements.
print(vals.typecode)      # Returns the typecode of the array i.e. i, I, B , etc

(140560996643408, 5)
i


In [ ]:
vals.reverse()             # Reverse does not return any value. This only reverses the whole array.

In [ ]:
print(vals)
print(c[0])

array('i', [5, 4, 3, 2, 1])
A


In [ ]:
#################### How to print array elements one by one #############
# from array import *
vals = array('i', [11,21,31,-4,5])

In [ ]:
for i in range(len(vals)):         # this works
    print(vals[i])

11
21
31
-4
5


In [ ]:
for i in vals:             # this works
    print(i)

11
21
31
-4
5


In [ ]:
i = 0                      # this also works
while i<len(vals):
    print(vals[i])
    i+=1

11
21
31
-4
5


In [ ]:
############Coping one array to other #####################
vals = array('i', [1,2,3,-4,5])

newarr = array(vals.typecode, (a*2 for a in vals)) # copied double of each number
print(newarr)

array('i', [2, 4, 6, -8, 10])


In [ ]:
1############### User input to an array #####################

arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)

print(arr)

Enter the length of an array 2
Enter a value 1
Enter a value 2
array('i', [1, 2])


In [ ]:
############# Searching an element in the array ########################
arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)

Key = int(input("Enter the value to be searched "))
k = 0
for item in arr:
    if item==Key:
        print("Item found on ", k)
        break
    k+=1

print("Item found on ", arr.index(Key))

Enter the length of an array 3
Enter a value 10
Enter a value 34
Enter a value 23
Enter the value to be searched 34
Item found on  1
Item found on  1


Numpy library

In [ ]:
####################### numpy ############################
"""
1. Helps in dealing with multi-dimensional array.
2. This does not come with the default packages of python. We need to install it separately.
3. Use "! pip3 install numpy" to install numpy.
"""

In [ ]:
# from numpy import *
import numpy as np

In [ ]:
print(np.__version__)

1.25.2


In [ ]:
vals = np.array([1,2,3,-4,5.6]) # typecode is not mandatory.
vals1 = np.array([1,2,3,-4,5.6], float) # Explicit Conversion
print(vals)
print(vals1)

[ 1.   2.   3.  -4.   5.6]
[ 1.   2.   3.  -4.   5.6]


Single-dimensional arrays, behave similar to row vectors

In [ ]:
x = np.array([1, 2, 3, 4, 5]) # Argument is a list
x

array([1, 2, 3, 4, 5])

In [ ]:
np.shape(x)
x.shape

(5,)

In [ ]:
x1 = np.array([[6,7,8,9,0]]) # Arg is list oif lists
print(x1)

[[6 7 8 9 0]]


In [ ]:
x1.shape

(1, 5)

In [ ]:
# x1 = np.array((5,3))
# print(np.shape(x1))

In [ ]:
print('x =', x, type(x), x.dtype)

x = [1 2 3 4 5] <class 'numpy.ndarray'> int64


In [ ]:
print('x =', x, x.dtype)

x = [1 2 3 4 5] int64


In [ ]:
print('x1 =', x1)

x1 = [[6 7 8 9 0]]


In [ ]:
print(np.shape(x), np.shape(x1))#, x.shape(), x1.shape())

(5,) (1, 5)


In [ ]:
y = x1 + 5
print('y =', y)

y = [[11 12 13 14  5]]


In [ ]:
z = x1 * 2
print('z =', z)

z = [[12 14 16 18  0]]


Matrices: Two-dimensional arrays

In [ ]:
A = np.array([
               [1, 2, 3, 4],
               [4, 5, 6, 6],
               [7, 8, 9, 7]
            ])

In [ ]:
print(A, A.shape, np.shape(A))

[[1 2 3 4]
 [4 5 6 6]
 [7 8 9 7]] (3, 4) (3, 4)


In [ ]:
C = A + 10
print(C)

[[11 12 13 14]
 [14 15 16 16]
 [17 18 19 17]]


In [ ]:
print('')

D = A * 3
print(D)


[[ 3  6  9 12]
 [12 15 18 18]
 [21 24 27 21]]


Compatible operations for matrices and vectors

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [ ]:
x = np.array([1,2,3])
print(x)
print(A + x)

[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
x = np.array([
                [1],
                [2],
                [3]
            ])
print(x)
print(A + x)

[[1]
 [2]
 [3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

inner = np.dot(x, y)

In [ ]:
print(inner)

14


In [ ]:
outer = np.outer(x,y)

print(outer)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


Random matrices

In [ ]:
A = np.random.rand(5,3)
print(A)

[[0.5870186  0.99525388 0.28779719]
 [0.0334819  0.58154173 0.4686894 ]
 [0.77412359 0.44908715 0.52704374]
 [0.35722455 0.15919252 0.92392068]
 [0.9496712  0.43947961 0.09619683]]


In [ ]:
print('')

In [ ]:
x = np.random.rand(5)
print(x, type(x), x.shape)

# Will not work
#print(A + x)

[0.70490823 0.70735303 0.24538845 0.52119871 0.99590203] <class 'numpy.ndarray'> (5,)


In [ ]:
x = np.random.randint(-1000,1000,(5,5))
print(x)

[[ -93 -727 -559  474  397]
 [  24 -970  208  482  -46]
 [-133 -218  920  928 -473]
 [ 645 -709  586 -297  859]
 [ -19   51  562   63 -282]]


Reshaping matrices

In [ ]:
x = np.random.rand(12)
print(x, type(x), x.shape)

[0.9701297  0.92087976 0.91189588 0.1809473  0.87333039 0.89640485
 0.17556094 0.33181327 0.19240063 0.09118428 0.21864953 0.80995875] <class 'numpy.ndarray'> (12,)


In [ ]:
y = np.reshape(x,(3,4))
print(y)

[[0.9701297  0.92087976 0.91189588 0.1809473 ]
 [0.87333039 0.89640485 0.17556094 0.33181327]
 [0.19240063 0.09118428 0.21864953 0.80995875]]


In [ ]:
x = np.array([x])
print(x,x.shape)

[[0.85159163 0.85629943 0.38481765 0.40512738 0.67846867 0.54103465
  0.24424945 0.36278903 0.91932666 0.42005677 0.95147435 0.77771016]] (1, 12)


In [ ]:
print('')

y = np.reshape(x,(3,4))
print(y)


[[0.85159163 0.85629943 0.38481765 0.40512738]
 [0.67846867 0.54103465 0.24424945 0.36278903]
 [0.91932666 0.42005677 0.95147435 0.77771016]]


In [ ]:
A = np.random.rand(5,3)
print(A, type(A), A.shape)

[[0.2317567  0.03867235 0.98302487]
 [0.43833177 0.91115864 0.01786635]
 [0.3134215  0.64857424 0.40522703]
 [0.55202169 0.93636933 0.52532516]
 [0.38561227 0.21059235 0.97746494]] <class 'numpy.ndarray'> (5, 3)


In [ ]:
y = np.reshape(A,(3,5))
print(y)

[[0.2317567  0.03867235 0.98302487 0.43833177 0.91115864]
 [0.01786635 0.3134215  0.64857424 0.40522703 0.55202169]
 [0.93636933 0.52532516 0.38561227 0.21059235 0.97746494]]


In [ ]:
print('')

x = np.random.rand(5)
print(x)

# Will not work
#print(A + x)

y = np.reshape(x,(5,1))
print(y)


[0.32698104 0.35815496 0.27309392 0.1787285  0.95255622]
[[0.32698104]
 [0.35815496]
 [0.27309392]
 [0.1787285 ]
 [0.95255622]]


In [ ]:
print('')

print(A + y)


[[0.70785086 0.69783445 0.46994647]
 [0.80021812 0.6905571  1.05513412]
 [0.30414187 0.42633558 0.86318423]
 [1.15342496 0.97074165 0.71017076]
 [1.00069857 1.32250836 1.87688081]]


Combining (or stacking) matrices

In [ ]:
x = np.random.rand(3)
print(x)
y = np.random.rand(3)
print(y)

[0.21489174 0.76421787 0.1474072 ]
[0.00118686 0.42133785 0.91576383]


In [ ]:
z1 = np.vstack((x, y))
print(z, z.shape)

[[0.21489174 0.76421787 0.1474072 ]
 [0.00118686 0.42133785 0.91576383]] (2, 3)


In [ ]:
z2 = np.hstack((x, y))
print(z, type(z), z.shape)

[[0.21489174 0.76421787 0.1474072 ]
 [0.00118686 0.42133785 0.91576383]] <class 'numpy.ndarray'> (2, 3)


In [ ]:
z3 = np.random.rand(2,3)

In [ ]:
z4 = np.hstack((z1, z3))
z4.shape

(2, 6)

<b>Exercise:</b> Create two arrays of size 3x5 initialized with random integers drawn from (-100,100) and then vertically & horizontally stack them.

In [ ]:
x1 = np.random.randint(-100,100,(3,5))
x2 = np.random.randint(-100,100,(3,5))
vX = np.vstack((x1,x2))
hX = np.hstack((x1,x2))
print(vX, '\n', hX)

[[  28  -23   -9   81   20]
 [ -64  -99   94  -49   25]
 [  43   13  -72   27  -59]
 [ -49  -83    5  -20   54]
 [  19   29   56   -5   -7]
 [ -50 -100   49   30  -69]] 
 [[  28  -23   -9   81   20  -49  -83    5  -20   54]
 [ -64  -99   94  -49   25   19   29   56   -5   -7]
 [  43   13  -72   27  -59  -50 -100   49   30  -69]]


Dimension and shape of numpy arrays

In [ ]:
A = np.random.rand(5,1)
print(A.ndim)
print(A.shape)

2
(5, 1)


In [ ]:
print('')

x = np.random.rand(5,3,10,25)
print(x.ndim)
print(x.shape)
# print(x)


4
(5, 3, 10, 25)


Functions to create a few special Matrices

In [ ]:
x = np.array([[1,2,3,4], [5,6,7,8]])
y = np.array(((1,2,3,4), (5,6,7,8)))
print(x, type(x), x.shape)
print(y, type(y), y.shape)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)


In [ ]:
arr1 = np.zeros(15, int) # Array of size 15. All are initialized to 0s. By default, the  values are float.
#arr1[1] = 3
print(arr1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(np.zeros((3,2), dtype=int)) # The shape e.g (3,2) should be a tuple

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
zf = np.zeros((3,2))
zi = np.zeros((3,2),dtype=int)

In [ ]:
print(type(zf), type(zi), zf.dtype, zi.dtype)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> float64 int64


In [ ]:
arr1 = np.ones(15, int) # Array of size 15. All are initialized to 1s. By default, the  values are float.
#arr1[1] = 3
print(arr1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
print(np.ones((5,5)))

print('')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [ ]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
arr1 = np.arange(0,15,2) # Parameters are start, stop, steps. Here, it is step not a part.
#arr1[1] = 3
print(arr1)

[ 0  2  4  6  8 10 12 14]


In [ ]:
x = list(range(0,9,2))
print(x)

[0, 2, 4, 6, 8]


In [ ]:
A = np.arange(0,9,2)

print(A, A.ndim, A.shape, type(A), A.dtype)

[0 2 4 6 8] 1 (5,) <class 'numpy.ndarray'> int64


In [ ]:
A = np.arange(9)
B = np.reshape(A, (3,3))

print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<b>Exercise:</b> Use np.arrange() function to create an array of size 4x2 where the elements will start from 0 to 14 (with step size 2) in row major oder

In [ ]:
A = np.arange(0,15,2)
B = np.reshape(A, (4,2))
print(B)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


In [ ]:
arr = np.linspace(0,15,25) # Parameters are start, stop, parts. Default step is 50. As it is step values are by default float here.
#arr[1] = 3
print(arr, arr.shape)

NameError: name 'np' is not defined

In [ ]:
arr = np.logspace(1,40,5) #Array will be devided into 5 parts. Start: 10^1 end: 10^40. The start to end will be divided into 5 parts.
#arr[1] = 3
print(arr)
print('%.2f' %arr[1])

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
56234132519.03


Operations on numpy array

In [ ]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5])
arr2 = np.zeros(5, int)

In [ ]:
# Want to add a number with each element of the array #######

In [ ]:
##### 1st approach #######

for i in range(len(arr)):
    arr[i] = arr[i] + 5

print(arr)

[ 6  7  8  9 10]


In [ ]:
##### 2nd approach ######
arr = arr + 10
print(arr)

[16 17 18 19 20]


In [ ]:
# Want to add 2 arrays #######

In [ ]:
##### 1st approach #######

for i in range(len(arr)):
    arr2[i] = arr[i] + arr1[i]

print(arr2)

[17 19 21 23 25]


In [ ]:
# ##### 2nd approach ######
arr3 = arr + arr1 ### Vectorized Operation (Was getting appended without numpy right?)
print(arr3)

[17 19 21 23 25]


Numpy array operations: max, argmax, min, argmin, sort, argsort </h2>

In [ ]:
# x = np.array([5,4,1,8,7,3,9,2,6])
x = np.random.randint(1,100,15)
print(x)

[95 99 84 47 80 68 19 14 84  8 47 33 16 95 66]


In [ ]:
print(np.max(x))

99


In [ ]:
print(np.argmax(x))

1


In [ ]:
print('')
print(np.min(x))
print(np.argmin(x))


8
9


In [ ]:
print('')
print(np.sort(x))
print(np.argsort(x))


[ 8 14 16 19 33 47 47 66 68 80 84 84 95 95 99]
[ 9  7 12  6 11  3 10 14  5  4  2  8  0 13  1]


In [ ]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
print(np.sin(arr)) ###### Sin values of each element ###########
print(np.cos(arr)) ###### Cos values of each element ###########
print(np.log(arr)) ###### log values of each element ###########
print(np.sqrt(arr)) ####### sqrt values of each element #########

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr3 = np.concatenate([arr, arr1])
print(np.concatenate([arr, arr1])) ########## Concatenating two arrays #############
print(arr3) ########## Concatenating two arrays #############

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


Array slicing

In [ ]:
# Colon operator
C = np.random.rand(10)
print(C)
print(C[1:5]) # C[start:end]
print(C[5:])
print(C[:], C)

[0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448]
[0.3959621  0.46238106 0.05943077 0.40983736]
[0.45362885 0.27904594 0.65275126 0.53673605 0.55481448]
[0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448] [0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448]


In [ ]:
# Colon operator
C = np.random.rand(3,5)
print(C)
print(C[1:3,1:4])

[[0.18638656 0.07861386 0.13422718 0.57694065 0.06553677]
 [0.70605391 0.76600616 0.5281187  0.44042072 0.88169362]
 [0.21287286 0.86182258 0.82693241 0.84736038 0.37811013]]
[[0.76600616 0.5281187  0.44042072]
 [0.86182258 0.82693241 0.84736038]]


<b>Exercise:</b> Generate an 1D array A with 20 elements randomly initialized with  the numbers in [0,15]. Create another 1D array B with 20 elements randomly initialized with the numbers in [0,1]. Sort A and apply the sorted indices of A on B.

In [ ]:
A = np.random.randint(0,15,(3,4))
B = np.random.rand(3,4)

In [ ]:
print(A,B)
ind = np.argsort(A)
print(np.sort(A), ind)

[[12  0 11  4]
 [ 8  5  6  2]
 [ 5  9  6 11]] [[0.19903673 0.54322573 0.50176205 0.22027842]
 [0.94039405 0.64317272 0.79319234 0.83447579]
 [0.02520253 0.58175136 0.32159502 0.9007976 ]]
[[ 0  4 11 12]
 [ 2  5  6  8]
 [ 5  6  9 11]] [[1 3 2 0]
 [3 1 2 0]
 [0 2 1 3]]


In [ ]:
print(B)
B2 = B
B2[0,:] = B2[0,ind[0,:]]
B2[1,:] = B2[1,ind[1,:]]
B2[2,:] = B2[2,ind[2,:]]
print(B2)

[[0.19903673 0.54322573 0.50176205 0.22027842]
 [0.94039405 0.64317272 0.79319234 0.83447579]
 [0.02520253 0.58175136 0.32159502 0.9007976 ]]
[[0.54322573 0.22027842 0.50176205 0.19903673]
 [0.83447579 0.64317272 0.79319234 0.94039405]
 [0.02520253 0.32159502 0.58175136 0.9007976 ]]


In [ ]:
temp = np.random.randint(1, 205, (5,5))
print(temp)

[[ 39  47  33  47  50]
 [ 20   5 168 158 157]
 [189 197  89 112 164]
 [ 55 179 192 202 200]
 [154  33   5  89  22]]


In [ ]:
print(temp.ndim, temp.shape)

2 (5, 5)


In [ ]:
print(temp[1,0])

20


Statistical operations: mean, var, std...

In [ ]:
x = np.array([5,4,1,8,7,3,9,2,6])
print(x)
x = np.random.randint(1,10, 9)
print(x)

print(np.mean(x))
print(np.var(x))
print(np.std(x))

[5 4 1 8 7 3 9 2 6]
[6 1 9 6 6 1 6 1 8]
4.888888888888889
8.543209876543209
2.9228769862146455


Boolean Element-Wise Operations

In [ ]:
x = np.random.rand(3,3)
print(x)

[[0.71278208 0.50116145 0.5352032 ]
 [0.34955667 0.08224069 0.89904175]
 [0.86188211 0.63196321 0.78152367]]


In [ ]:
y = (x>0.5)
print(y,y.dtype)

[[ True  True  True]
 [False False  True]
 [ True  True  True]] bool


Boolean 'Mask'

In [ ]:
x = np.random.rand(3,3)
print(x)

[[0.62441862 0.05277173 0.13631861]
 [0.87749527 0.85386434 0.39366079]
 [0.30771496 0.41661061 0.60021   ]]


In [ ]:
mask = x > 0.5
print(mask)

[[ True False False]
 [ True  True False]
 [False False  True]]


In [ ]:
print(x[mask])
# print(x)

[0.62441862 0.87749527 0.85386434 0.60021   ]


In [ ]:
x[mask] = 0
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
### Q: Set all the elements (which are not satisfying the condition) to 0

In [ ]:
x = np.random.rand(3,3)

mask = x > 0.5
x[mask] = 0
print(x)


[[0.26336041 0.3791179  0.        ]
 [0.         0.         0.45667854]
 [0.         0.         0.01231159]]


In [ ]:
x = np.random.rand(3,3)
print(x)

[[0.12247162 0.36588404 0.97864954]
 [0.5428958  0.5834374  0.31346318]
 [0.41430306 0.68377941 0.37135078]]


In [ ]:
r, c = np.where(x == 50)
print(r, c)

[0 0 1 2] [0 1 2 2]


In [ ]:
index = np.where(x == 0)
print(index)

(array([0, 1, 1, 2, 2]), array([2, 0, 1, 0, 1]))


In [ ]:
x = np.array([1,2,3,4,5])

def f(x):
    return x**2

for i in x:
    print(i,f(i))

1 1
2 4
3 9
4 16
5 25


In [ ]:
print(np.random.rand(3, 2,2,3))

[[[[0.64477566 0.87165385 0.55553064]
   [0.12148573 0.97575567 0.56203657]]

  [[0.85966492 0.87020211 0.18778757]
   [0.69256603 0.35067682 0.93721464]]]


 [[[0.37014304 0.20289258 0.07207275]
   [0.76887863 0.87475974 0.75287849]]

  [[0.22803713 0.1048985  0.06468587]
   [0.22402321 0.6845372  0.8152341 ]]]


 [[[0.56987228 0.01058043 0.21627109]
   [0.82732755 0.93612811 0.94977088]]

  [[0.80095807 0.79615319 0.84137467]
   [0.16527545 0.47264677 0.59266749]]]]


In [ ]:
x = np.array(  [
    [[2,1],
     [3,5]],
    [[0,1],
     [2,3]],
    [[1,2],
     [9,5]]
])
print(x)

[[[2 1]
  [3 5]]

 [[0 1]
  [2 3]]

 [[1 2]
  [9 5]]]


In [ ]:
print(x.ndim, x.shape)

3 (3, 2, 2)


### Some important operations in numpy

In [ ]:
r2 = np.random.randint(1,10,(4,5))
print(r2)

[[6 1 6 8 2]
 [1 5 1 9 7]
 [9 1 4 5 9]
 [4 9 9 9 5]]


In [ ]:
print(np.empty((5,5)))

[[4.68183507e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 1.63041663e-322 6.56343979e-310 6.56343979e-310
  1.42290906e-321]]


In [ ]:
y = np.empty_like(r2)
print(y)

[[      94870469064961                    0 -2872391897746907687
       139436943957744      139437370179824]
 [-4452990780830496973      139436943958192      139437370179824
  -1684579016451738073      139436943958576]
 [     139437370179824  -568090647327120271      139436943957360
       139437370179824  4170112331781509762]
 [     139436943959152      139437370179824  1812656245910512912
       139436943959984      139437370179824]]


In [ ]:
y = np.zeros_like(r2)
print(y)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
y = np.ones_like(r2)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
print(r2.T) # Transpose
print('\n')
print(np.transpose(r2))

[[8 6 5 9]
 [2 4 9 5]
 [1 4 3 4]
 [3 8 2 5]
 [5 9 3 8]]


[[8 6 5 9]
 [2 4 9 5]
 [1 4 3 4]
 [3 8 2 5]
 [5 9 3 8]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [ ]:
print(np.sum(x))  # Compute sum of all elements; prints "10"

10


In [ ]:
x = np.random.randint(1,100,(6,8))
print(x)
print(np.sum(x))
print(x.sum())

[[64 71 32 14 25 92 32 81]
 [ 8 62  9  3 73 78 18 27]
 [41 31 29 70 93 70 35  3]
 [77 69 94 61 48 20 68 20]
 [58 47  1 33 21 55  1 31]
 [24  7 96 10 13 59 47  4]]
2025
2025


In [ ]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

[272 287 261 191 273 374 201 166]


In [ ]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[411 278 372 457 247 260]


In [ ]:
print(np.sqrt(x))

[[8.         8.42614977 5.65685425 3.74165739 5.         9.59166305
  5.65685425 9.        ]
 [2.82842712 7.87400787 3.         1.73205081 8.54400375 8.83176087
  4.24264069 5.19615242]
 [6.40312424 5.56776436 5.38516481 8.36660027 9.64365076 8.36660027
  5.91607978 1.73205081]
 [8.77496439 8.30662386 9.69535971 7.81024968 6.92820323 4.47213595
  8.24621125 4.47213595]
 [7.61577311 6.8556546  1.         5.74456265 4.58257569 7.41619849
  1.         5.56776436]
 [4.89897949 2.64575131 9.79795897 3.16227766 3.60555128 7.68114575
  6.8556546  2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6], [7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [ ]:
print(x+y)

[[ 6  8]
 [10 12]]


<b>Exercise:</b> Define a random matrix of shape 7x8. Fetch the number of rows and columns programatically. Then manipulate each element of the matrix with the following formula: x = sqrt((x+5)/10), x refers to the element of the matrix.

In [ ]:
A = np.random.randint(1,50,(7,8))
print(A)
row, col = A.shape
print(row, col)
for i in range(row):
    for j in range(col):
        A[i,j] = np.sqrt((A[i,j]+5)/10)
print(A)

[[26  9 40 26 28 14 37 25]
 [38 38 40 28 11 32 16 32]
 [23 10 19 14 21 26 33 33]
 [ 7  5 28 44 39 13 19 19]
 [37 28  5 11 16  9 40 40]
 [16 33 35 49 10  8 27 25]
 [ 8 16 22  9 42 47  2 23]]
7 8
[[1 1 2 1 1 1 2 1]
 [2 2 2 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 2 2 1 1 1]
 [2 1 1 1 1 1 2 2]
 [1 1 2 2 1 1 1 1]
 [1 1 1 1 2 2 0 1]]


In [ ]:
a2d = np.array([[1,2,3],[4,5,6]])
b2d = np.array([[10,4,6],[2,4,6]])
print(a2d, a2d.shape)
print(b2d, b2d.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[10  4  6]
 [ 2  4  6]] (2, 3)


In [ ]:
print(a2d.shape[1])

r, c = b2d.shape
print(r,c)

3
2 3


In [ ]:
c2d = a2d.T # Transpose
print(c2d)
print(a2d)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Element wise multiplication
d2d = a2d * b2d
print(d2d)

[[10  8 18]
 [ 8 20 36]]


In [ ]:
d2d = np.multiply(a2d, b2d)
print(d2d)

[[10  8 18]
 [ 8 20 36]]


In [ ]:
print(a2d.shape, b2d.shape, c2d.shape)

(2, 3) (2, 3) (3, 2)


In [ ]:
# Matrix multiplication
e2d = np.dot(a2d,c2d)
print(e2d)

[[14 32]
 [32 77]]


In [ ]:
e2d = np.matmul(a2d,c2d)
print(e2d)

[[14 32]
 [32 77]]


In [ ]:
f2d = np.matmul(b2d,c2d)
print(f2d)

[[36 96]
 [28 64]]


In [ ]:
det1 = np.linalg.det(e2d)
print(det1)

54.00000000000001


In [ ]:
eig, eig_vec = np.linalg.eig(e2d)
print(eig)
print(eig_vec)

[ 0.59732747 90.40267253]
[[-0.92236578 -0.3863177 ]
 [ 0.3863177  -0.92236578]]


In [ ]:
inv1 = np.linalg.inv(e2d)
print(inv1)

[[ 1.42592593 -0.59259259]
 [-0.59259259  0.25925926]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = a[:2, 1:3] #Last exclusive
print(b)

[[2 3]
 [6 7]]


In [ ]:
b[0, 1] = 77
print(b)

[[ 2 77]
 [ 6  7]]


In [ ]:
print(a)

[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
################## Coping one array to other ####################
"""
Three types of copies-
                    1. Aliasing.
                    2. Shallow Copy.
                    3. Deep Copy.
"""

'\nThree types of copies-\n                    1. Aliasing.\n                    2. Shallow Copy.\n                    3. Deep Copy.\n'

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr2 = arr             # Only Aliasing
print(arr2)
print(id(arr), id(arr2)) #In memory, we have only one instance of each element. Only duplicate reference variables are created.


[1 2 3 4 5]
132844210239216 132844210239216


In [ ]:
arr2 = arr[2:3]
print(arr2)

[3]


In [ ]:
arr2

array([3])

In [ ]:
arr2[0] = arr2[0] + 1
print(arr2)

[4]


In [ ]:
arr

array([1, 2, 4, 4, 5])

In [ ]:
arr3 = arr.view() # shallow copy ---> changing in one affects the other.
arr[1] = 90
print(arr)
print(arr3)
print(id(arr), id(arr3)) # Addresses are different i.e. two copies of each elements are now created.

[ 1 90  3  4  5]
[ 1 90  3  4  5]
132844210338288 132844210515344


In [ ]:
arr3 = arr.copy() # deep copy ---> changing in one does not affect the other.
arr[1] = 90
print(arr)
print(arr3)
print(id(arr), id(arr3))

[ 1 90  3  4  5]
[1 2 3 4 5]
132844210516496 132844210519280


In [ ]:
c = np.copy(a)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
c[0,0] = 105
print(c)
print(a)

[[105   2  77   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1  2 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [ ]:
print(x+v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<b>Exercise:</b> Create a random array A of size 5x4. Using np.tile() function, add a random vector of size 4 with first three rows of A and add another random vector of size 4 with last two rows of A.

In [ ]:
A = np.random.randint(1,100,(5,4))
vec1 = np.random.randint(0,2,4)
vec2 = np.random.randint(0,2,4)
print(A)
print(vec1)
print(vec2)

[[77  8 51  2]
 [81 22 92 32]
 [77 85  6 59]
 [77  8 51 86]
 [25  3 22 80]]
[0 1 1 1]
[1 0 0 1]


In [ ]:
A[:3,:] = A[:3,:]+vec1
A[3:,:] = A[3:,:]+vec2
print(A)

[[84 81 85 42]
 [33 98 62  3]
 [44 60 58 98]
 [85 14  7  9]
 [ 4 85 17 97]]


In [ ]:
v_1 = np.tile(vec1,(3,1))
print(v_1)
v_2 = np.tile(vec2,(2,1))
print(v_2)

[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
[[0 0 1 0]
 [0 0 1 0]]


In [ ]:
v = np.vstack((v_1, v_2))
print(v)

[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]]


In [ ]:
print(A+v)

[[84 81 85 43]
 [33 98 62  4]
 [44 60 58 99]
 [85 14  8  9]
 [ 4 85 18 97]]


Working with matrices

In [ ]:
arr1 = np.array([
            [1,2,3,7],
            [4,5,6,9]
            ])

m = np.matrix(arr1)  # Converting a 2D array into a matrix format
m

matrix([[1, 2, 3, 7],
        [4, 5, 6, 9]])

In [ ]:
m1 = np.matrix ('1 2 3;4 5 6;7 8 9') # Converting a string into a matrix format (even this works)
print(m) # Output is same but with this conversion, you can do planty of additional oprations.
print(m1)
print(np.diagonal(m1)) # print the diagonal elements of the matrix
print(m1.min()) # Finding Minimum of a matrix
print(m1.max()) # Finding Maximum of a matrix

[[1 2 3 7]
 [4 5 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
1
9


In [ ]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))

mat = []
mat1 = []
print("Enter the entries rowwise:")

for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    mat.append(a)
m = np.matrix(mat)

for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    mat1.append(a)
m2 = np.matrix(mat1)

for i in range(R):
    for j in range(C):
        mat[i][j] = mat[i][j] + mat1[i][j]
m = m + m2
print("The sum is = \n")
for i in range(R):
    for j in range(C):
        print(mat[i][j], end = " ")
    print()

print("---------------")
print("The sum is = \n")
print(m)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
5
6
7
8
The sum is = 

6 8 
10 12 
---------------
The sum is = 

[[ 6  8]
 [10 12]]


<p><h2 style="color:#784212" align="left">References</h2></p>
<p style="font-size:17px">
a) <a href='https://docs.scipy.org/doc/numpy/' style="text-decoration: none">Numpy documentation<br style="line-height:25px"></a>
b) <a href='https://docs.scipy.org/doc/numpy/user/index.html' style="text-decoration: none">Numpy user guide<br style="line-height:25px"></a>
</p>