<h1 style="color:#6C3483" align = "center">Arrays and Numpy</h1>

Array Library

In [ ]:
######### Array in python #########
"""
1. Arrays are collection of homogeneous datatypes.
2. Types: i-->signed int, I --> unsigned int, f---> float, d--->double, L ---> unsigned Long, l ---> signed long,
u--->char.
"""

'\n1. Arrays are collection of homogeneous datatypes.\n2. Types: i-->signed int, I --> unsigned int, f---> float, d--->double, L ---> unsigned Long, l ---> signed long,\nu--->char.\n'

In [ ]:
from array import *               # By default arrays are not supported, you need to import the array module.
# import array as arr

In [ ]:
vals = array('i', [1,2,3,4,5])

In [ ]:
vals1 = array('i', [1,2,3,4,6]) # Heterogenous data not supported

In [ ]:
val3 = vals+vals1                # not getting elementwise sums. One is appended with other. Elementwise sum in numpy.
val3

array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 6])

In [ ]:
vals = array('I', [1,2,3,-4,5])  # Unsigned int, both positive and negative values are not supported together

OverflowError: can't convert negative value to unsigned int

In [ ]:
vals1 = array('i', [1,2,3,-4,5]) # Signed int, both positive and negative values are supported

In [ ]:
cval3 = vals+vals1                # not getting elementwise sums. One is appended with other. Elementwise sum in numpy.
val3

array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 6])

In [ ]:
c = array('u', ['A', ' ', 'B', ' ', 'C'])   # u (unicode) --> charecters
c

array('u', 'A B C')

In [ ]:
print(vals.buffer_info()) # Returns a tuple with initial address of the array with the number of elements.
print(vals.typecode)      # Returns the typecode of the array i.e. i, I, B , etc

(140560996643408, 5)
i


In [ ]:
vals.reverse()             # Reverse does not return any value. This only reverses the whole array.

In [ ]:
print(vals)
print(c[0])

array('i', [5, 4, 3, 2, 1])
A


In [ ]:
#################### How to print array elements one by one #############
# from array import *
vals = array('i', [11,21,31,-4,5])

In [ ]:
for i in range(len(vals)):         # this works
    print(vals[i])

11
21
31
-4
5


In [ ]:
for i in vals:             # this works
    print(i)

11
21
31
-4
5


In [ ]:
i = 0                      # this also works
while i<len(vals):
    print(vals[i])
    i+=1

11
21
31
-4
5


In [ ]:
############Coping one array to other #####################
vals = array('i', [1,2,3,-4,5])

newarr = array(vals.typecode, (a*2 for a in vals)) # copied double of each number
print(newarr)

array('i', [2, 4, 6, -8, 10])


In [ ]:
1############### User input to an array #####################

arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)

print(arr)

Enter the length of an array 2
Enter a value 1
Enter a value 2
array('i', [1, 2])


In [ ]:
############# Searching an element in the array ########################
arr = array('i', [])
n = int(input("Enter the length of an array "))

for i in range(n):
    x = int(input("Enter a value "))
    arr.append(x)

Key = int(input("Enter the value to be searched "))
k = 0
for item in arr:
    if item==Key:
        print("Item found on ", k)
        break
    k+=1

print("Item found on ", arr.index(Key))

Enter the length of an array 3
Enter a value 10
Enter a value 34
Enter a value 23
Enter the value to be searched 34
Item found on  1
Item found on  1


Numpy library

In [ ]:
####################### numpy ############################
"""
1. Helps in dealing with multi-dimensional array.
2. This does not come with the default packages of python. We need to install it separately.
3. Use "! pip3 install numpy" to install numpy.
"""

In [ ]:
# from numpy import *
import numpy as np

In [ ]:
print(np.__version__)

1.25.2


In [ ]:
vals = np.array([1,2,3,-4,5.6]) # typecode is not mandatory.
vals1 = np.array([1,2,3,-4,5.6], float) # Explicit Conversion
print(vals)
print(vals1)

[ 1.   2.   3.  -4.   5.6]
[ 1.   2.   3.  -4.   5.6]


Single-dimensional arrays, behave similar to row vectors

In [ ]:
x = np.array([1, 2, 3, 4, 5]) # Argument is a list
x

array([1, 2, 3, 4, 5])

In [ ]:
np.shape(x)
x.shape

(5,)

In [ ]:
x1 = np.array([[6,7,8,9,0]]) # Arg is list oif lists
print(x1)

[[6 7 8 9 0]]


In [ ]:
x1.shape

(1, 5)

In [ ]:
# x1 = np.array((5,3))
# print(np.shape(x1))

In [ ]:
print('x =', x, type(x), x.dtype)

x = [1 2 3 4 5] <class 'numpy.ndarray'> int64


In [ ]:
print('x =', x, x.dtype)

x = [1 2 3 4 5] int64


In [ ]:
print('x1 =', x1)

x1 = [[6 7 8 9 0]]


In [ ]:
print(np.shape(x), np.shape(x1))#, x.shape(), x1.shape())

(5,) (1, 5)


In [ ]:
y = x1 + 5
print('y =', y)

y = [[11 12 13 14  5]]


In [ ]:
z = x1 * 2
print('z =', z)

z = [[12 14 16 18  0]]


Matrices: Two-dimensional arrays

In [ ]:
A = np.array([
               [1, 2, 3, 4],
               [4, 5, 6, 6],
               [7, 8, 9, 7]
            ])

In [ ]:
print(A, A.shape, np.shape(A))

[[1 2 3 4]
 [4 5 6 6]
 [7 8 9 7]] (3, 4) (3, 4)


In [ ]:
C = A + 10
print(C)

[[11 12 13 14]
 [14 15 16 16]
 [17 18 19 17]]


In [ ]:
print('')

D = A * 3
print(D)


[[ 3  6  9 12]
 [12 15 18 18]
 [21 24 27 21]]


Compatible operations for matrices and vectors

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [ ]:
x = np.array([1,2,3])
print(x)
print(A + x)

[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
x = np.array([
                [1],
                [2],
                [3]
            ])
print(x)
print(A + x)

[[1]
 [2]
 [3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

inner = np.dot(x, y)

In [ ]:
print(inner)

14


In [ ]:
outer = np.outer(x,y)

print(outer)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


Random matrices

In [ ]:
A = np.random.rand(5,3)
print(A)

[[0.5870186  0.99525388 0.28779719]
 [0.0334819  0.58154173 0.4686894 ]
 [0.77412359 0.44908715 0.52704374]
 [0.35722455 0.15919252 0.92392068]
 [0.9496712  0.43947961 0.09619683]]


In [ ]:
print('')

In [ ]:
x = np.random.rand(5)
print(x, type(x), x.shape)

# Will not work
#print(A + x)

[0.70490823 0.70735303 0.24538845 0.52119871 0.99590203] <class 'numpy.ndarray'> (5,)


In [ ]:
x = np.random.randint(-1000,1000,(5,5))
print(x)

[[ -93 -727 -559  474  397]
 [  24 -970  208  482  -46]
 [-133 -218  920  928 -473]
 [ 645 -709  586 -297  859]
 [ -19   51  562   63 -282]]


Reshaping matrices

In [ ]:
x = np.random.rand(12)
print(x, type(x), x.shape)

[0.9701297  0.92087976 0.91189588 0.1809473  0.87333039 0.89640485
 0.17556094 0.33181327 0.19240063 0.09118428 0.21864953 0.80995875] <class 'numpy.ndarray'> (12,)


In [ ]:
y = np.reshape(x,(3,4))
print(y)

[[0.9701297  0.92087976 0.91189588 0.1809473 ]
 [0.87333039 0.89640485 0.17556094 0.33181327]
 [0.19240063 0.09118428 0.21864953 0.80995875]]


In [ ]:
x = np.array([x])
print(x,x.shape)

[[0.85159163 0.85629943 0.38481765 0.40512738 0.67846867 0.54103465
  0.24424945 0.36278903 0.91932666 0.42005677 0.95147435 0.77771016]] (1, 12)


In [ ]:
print('')

y = np.reshape(x,(3,4))
print(y)


[[0.85159163 0.85629943 0.38481765 0.40512738]
 [0.67846867 0.54103465 0.24424945 0.36278903]
 [0.91932666 0.42005677 0.95147435 0.77771016]]


In [ ]:
A = np.random.rand(5,3)
print(A, type(A), A.shape)

[[0.2317567  0.03867235 0.98302487]
 [0.43833177 0.91115864 0.01786635]
 [0.3134215  0.64857424 0.40522703]
 [0.55202169 0.93636933 0.52532516]
 [0.38561227 0.21059235 0.97746494]] <class 'numpy.ndarray'> (5, 3)


In [ ]:
y = np.reshape(A,(3,5))
print(y)

[[0.2317567  0.03867235 0.98302487 0.43833177 0.91115864]
 [0.01786635 0.3134215  0.64857424 0.40522703 0.55202169]
 [0.93636933 0.52532516 0.38561227 0.21059235 0.97746494]]


In [ ]:
print('')

x = np.random.rand(5)
print(x)

# Will not work
#print(A + x)

y = np.reshape(x,(5,1))
print(y)


[0.32698104 0.35815496 0.27309392 0.1787285  0.95255622]
[[0.32698104]
 [0.35815496]
 [0.27309392]
 [0.1787285 ]
 [0.95255622]]


In [ ]:
print('')

print(A + y)


[[0.70785086 0.69783445 0.46994647]
 [0.80021812 0.6905571  1.05513412]
 [0.30414187 0.42633558 0.86318423]
 [1.15342496 0.97074165 0.71017076]
 [1.00069857 1.32250836 1.87688081]]


Combining (or stacking) matrices

In [ ]:
x = np.random.rand(3)
print(x)
y = np.random.rand(3)
print(y)

[0.21489174 0.76421787 0.1474072 ]
[0.00118686 0.42133785 0.91576383]


In [ ]:
z1 = np.vstack((x, y))
print(z, z.shape)

[[0.21489174 0.76421787 0.1474072 ]
 [0.00118686 0.42133785 0.91576383]] (2, 3)


In [ ]:
z2 = np.hstack((x, y))
print(z, type(z), z.shape)

[[0.21489174 0.76421787 0.1474072 ]
 [0.00118686 0.42133785 0.91576383]] <class 'numpy.ndarray'> (2, 3)


In [ ]:
z3 = np.random.rand(2,3)

In [ ]:
z4 = np.hstack((z1, z3))
z4.shape

(2, 6)

<b>Exercise:</b> Create two arrays of size 3x5 initialized with random integers drawn from (-100,100) and then vertically & horizontally stack them.

In [ ]:
x1 = np.random.randint(-100,100,(3,5))
x2 = np.random.randint(-100,100,(3,5))
vX = np.vstack((x1,x2))
hX = np.hstack((x1,x2))
print(vX, '\n', hX)

[[  28  -23   -9   81   20]
 [ -64  -99   94  -49   25]
 [  43   13  -72   27  -59]
 [ -49  -83    5  -20   54]
 [  19   29   56   -5   -7]
 [ -50 -100   49   30  -69]] 
 [[  28  -23   -9   81   20  -49  -83    5  -20   54]
 [ -64  -99   94  -49   25   19   29   56   -5   -7]
 [  43   13  -72   27  -59  -50 -100   49   30  -69]]


Dimension and shape of numpy arrays

In [ ]:
A = np.random.rand(5,1)
print(A.ndim)
print(A.shape)

2
(5, 1)


In [ ]:
print('')

x = np.random.rand(5,3,10,25)
print(x.ndim)
print(x.shape)
# print(x)


4
(5, 3, 10, 25)


Functions to create a few special Matrices

In [ ]:
x = np.array([[1,2,3,4], [5,6,7,8]])
y = np.array(((1,2,3,4), (5,6,7,8)))
print(x, type(x), x.shape)
print(y, type(y), y.shape)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4)


In [ ]:
arr1 = np.zeros(15, int) # Array of size 15. All are initialized to 0s. By default, the  values are float.
#arr1[1] = 3
print(arr1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(np.zeros((3,2), dtype=int)) # The shape e.g (3,2) should be a tuple

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
zf = np.zeros((3,2))
zi = np.zeros((3,2),dtype=int)

In [ ]:
print(type(zf), type(zi), zf.dtype, zi.dtype)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> float64 int64


In [ ]:
arr1 = np.ones(15, int) # Array of size 15. All are initialized to 1s. By default, the  values are float.
#arr1[1] = 3
print(arr1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
print(np.ones((5,5)))

print('')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [ ]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
arr1 = np.arange(0,15,2) # Parameters are start, stop, steps. Here, it is step not a part.
#arr1[1] = 3
print(arr1)

[ 0  2  4  6  8 10 12 14]


In [ ]:
x = list(range(0,9,2))
print(x)

[0, 2, 4, 6, 8]


In [ ]:
A = np.arange(0,9,2)

print(A, A.ndim, A.shape, type(A), A.dtype)

[0 2 4 6 8] 1 (5,) <class 'numpy.ndarray'> int64


In [ ]:
A = np.arange(9)
B = np.reshape(A, (3,3))

print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<b>Exercise:</b> Use np.arrange() function to create an array of size 4x2 where the elements will start from 0 to 14 (with step size 2) in row major oder

In [ ]:
A = np.arange(0,15,2)
B = np.reshape(A, (4,2))
print(B)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


In [ ]:
arr = np.linspace(0,15,25) # Parameters are start, stop, parts. Default step is 50. As it is step values are by default float here.
#arr[1] = 3
print(arr, arr.shape)

[ 0.     0.625  1.25   1.875  2.5    3.125  3.75   4.375  5.     5.625
  6.25   6.875  7.5    8.125  8.75   9.375 10.    10.625 11.25  11.875
 12.5   13.125 13.75  14.375 15.   ] (25,)


In [ ]:
arr = np.logspace(1,40,5) #Array will be devided into 5 parts. Start: 10^1 end: 10^40. The start to end will be divided into 5 parts.
#arr[1] = 3
print(arr)
print('%.2f' %arr[1])

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
56234132519.03


Operations on numpy array

In [ ]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,2,3,4,5])
arr2 = np.zeros(5, int)

In [ ]:
# Want to add a number with each element of the array #######

In [ ]:
##### 1st approach #######

for i in range(len(arr)):
    arr[i] = arr[i] + 5

print(arr)

[ 6  7  8  9 10]


In [ ]:
##### 2nd approach ######
arr = arr + 10
print(arr)

[16 17 18 19 20]


In [ ]:
# Want to add 2 arrays #######

In [ ]:
##### 1st approach #######

for i in range(len(arr)):
    arr2[i] = arr[i] + arr1[i]

print(arr2)

[17 19 21 23 25]


In [ ]:
# ##### 2nd approach ######
arr3 = arr + arr1 ### Vectorized Operation (Was getting appended without numpy right?)
print(arr3)

[17 19 21 23 25]


Numpy array operations: max, argmax, min, argmin, sort, argsort </h2>

In [ ]:
# x = np.array([5,4,1,8,7,3,9,2,6])
x = np.random.randint(1,100,15)
print(x)

[95 99 84 47 80 68 19 14 84  8 47 33 16 95 66]


In [ ]:
print(np.max(x))

99


In [ ]:
print(np.argmax(x))

1


In [ ]:
print('')
print(np.min(x))
print(np.argmin(x))


8
9


In [ ]:
print('')
print(np.sort(x))
print(np.argsort(x))


[ 8 14 16 19 33 47 47 66 68 80 84 84 95 95 99]
[ 9  7 12  6 11  3 10 14  5  4  2  8  0 13  1]


In [ ]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
print(np.sin(arr)) ###### Sin values of each element ###########
print(np.cos(arr)) ###### Cos values of each element ###########
print(np.log(arr)) ###### log values of each element ###########
print(np.sqrt(arr)) ####### sqrt values of each element #########

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr3 = np.concatenate([arr, arr1])
print(np.concatenate([arr, arr1])) ########## Concatenating two arrays #############
print(arr3) ########## Concatenating two arrays #############

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


Array slicing

In [ ]:
# Colon operator
C = np.random.rand(10)
print(C)
print(C[1:5])
print(C[5:])
print(C[:], C)

[0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448]
[0.3959621  0.46238106 0.05943077 0.40983736]
[0.45362885 0.27904594 0.65275126 0.53673605 0.55481448]
[0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448] [0.38374141 0.3959621  0.46238106 0.05943077 0.40983736 0.45362885
 0.27904594 0.65275126 0.53673605 0.55481448]


In [ ]:
# Colon operator
C = np.random.rand(3,5)
print(C)
print(C[1:3,1:4])

[[0.18638656 0.07861386 0.13422718 0.57694065 0.06553677]
 [0.70605391 0.76600616 0.5281187  0.44042072 0.88169362]
 [0.21287286 0.86182258 0.82693241 0.84736038 0.37811013]]
[[0.76600616 0.5281187  0.44042072]
 [0.86182258 0.82693241 0.84736038]]


ndim

In [10]:
import numpy as np
p = np.array(56)
q = np.array([1,2,3,4,5])
r = np.array([[1,2,3],[4,5,6]])
s = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(type(p))
print(p.ndim)
print(q.ndim)
print(r.ndim)
print(s.ndim)

print("Arrays are")

print(p)
print(q)
print(r)
print(s)


<class 'numpy.ndarray'>
0
1
2
3
Arrays are
56
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
import numpy as np
ar1 = np.array([4,5,6])
ar2 = np.array([1,2,3])
ar3 = np.concatenate((ar1,ar2))
print(ar3)


[4 5 6 1 2 3]


In [22]:
import numpy as np
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6],[7,8]])
ar3 = np.concatenate((ar1,ar2),axis=0)
ar4 = np.concatenate((ar1,ar2),axis=1)

print("Axis 0 :" , ar3)
print("Axis 1 :", ar4)

Axis 0 : [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis 1 : [[1 2 5 6]
 [3 4 7 8]]
